### ISSUE TITLE
Resource issue when evaluating the factor-vae metric

### ISSUE THREAD

**Issue by mjpyeon** [google-research/disentanglement_lib#11]
When models are evaluated with factor-vae metric, `num_variance_estimate` (default 10000) samples are fed to `representation_function` (https://github.com/google-research/disentanglement_lib/blob/master/disentanglement_lib/evaluation/metrics/factor_vae.py#L57). So, users having ready-made NVIDIA GPUs cannot deal with 10000x64x64x3 inputs as a single batch. I tested with GTX TITAN Xp with 12GB memory and Tensorflow 1.13.1. Please modify the code to extract representations with `batch_size` and concatenate them.

**Comment by mseitzer** [comment]
I am affected by this as well, in particular with regards to the Neurips2019 Disentanglement Challenge, which depends on your lib. It would be nice if you could submit a timely fix so that we can participate in the challenge.

**Comment by obachem** [comment]
Thanks for bringing this to our attention. We have uploaded version 1.1 which should fix this issue.
