### ISSUE TITLE
Bug: Factor-VAE metric can only be evaluated if representation size equals number of latent factors

### ISSUE THREAD

**Issue by mseitzer** [google-research/disentanglement_lib#12]
Hi,

the latest changes in v1.1 introduced an assertion that prevents Factor-VAE to be evaluated if the number of dimensions of the representation is not equal to the number of latent variables of the dataset:

https://github.com/google-research/disentanglement_lib/blob/e2df8efb56466c83f118577456ce860350225156/disentanglement_lib/evaluation/metrics/factor_vae.py#L130

I am not 100% sure, but I think the metric should also be computable in the other case.

Again, this is problematic for the disentanglement challenge. As it ends this Friday, a quick fix would be appreciated :-)

**Comment by obachem** [comment]
Done, thanks for catching this.
