### ISSUE TITLE
Potential issue with FactorVAE discriminator loss

### ISSUE THREAD

**Issue by psoulos** [google-research/disentanglement_lib#16]
Hello,

I am writing about the [discrimnator loss for FactorVAE](https://github.com/google-research/disentanglement_lib/blob/master/disentanglement_lib/methods/unsupervised/vae.py#L242). Should the two values in `discr_loss` be negative? It seems like the `probs_z[:, 0]` is the probability that the sample comes from the joint distribution, but the line that I linked would encourage the values in `probs_z[:, 0]` to go towards 0 instead of 1.

**Comment by psoulos** [comment]
Sorry, I just realized that `-discr_loss` is minimized instead of `discr_loss`

**Comment by betterze** [comment]
Thank for the great implement, I have a related question. 

In DCI metric, dose the dimention D of code C (in 2 THEORETICAL FRAMEWORK of the paper) affect the output number? If so, how it affect disentanglement, completeness and informativeness? Can I use this metric to compare two latent codes  with different length?

Thank you very much for your help.

Best Wishes,

Alex
