### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by samarthbhargav** [google-research/disentanglement_lib#17]
I'm having trouble installing everything. Using setup.py installs tf2.0, which gives me several errors when I run `dlib_tests`. Can the authors please share a requirements.txt file / fix the setup.py file?

**Comment by obachem** [comment]
We will fix the setup.py file in an upcoming release. In the meantime, you could try to downgrade tensorflow and tensorflow-probability to an older version, which should restore functionality.

**Comment by samarthbhargav** [comment]
noted!
