### ISSUE TITLE
Do you consider to upgrade this to tf2 or pytorch?

### ISSUE THREAD

**Issue by erow** [google-research/disentanglement_lib#32]
I am sorry to say so, but I am struggling to modify the codes.

**Comment by luis-armando-perez-rey** [comment]
I also think this would be a valuable update to the code since this is a great disentanglement framework. It works fine now with Tensorflow but would be nice to remove all the warnings when running the code.

**Comment by bonheml** [comment]
I don't know what the plans are for this framework but I will be happy to contribute and do a tf2 version with Keras models on a new branch or something. @obachem let me know if this is something that could fit the roadmap of the framework.

**Comment by erow** [comment]
I created a pytorch version in https://gitee.com/microcloud/disentanglement_lib.
